import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import ContextAPI from "@/context/context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ContextAPI>
        <body>
          <Header/>
          <main>
          {children}
          </main>
        </body>
      </ContextAPI>
    </html>
  );
}
