import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import ContextAPI from "@/context/context";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ContextAPI>
        <body>
          <Header/>
          <main>
          {children}
          </main>
          <div className="h-2 bg-gradient-to-r from-[#F7E16A] to-[#AE6CE3]"></div>
          <Footer/>
        </body>
      </ContextAPI>
    </html>
  );
}
