name: deploy to production
on:
    workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Pull Request Code
      - name: Checkout Pull Request Code
        uses: actions/checkout@v3
      
      # Step 2: Deploy to Production
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID }} 
          working-directory: ./