name: deploy to staging
on:
    workflow_dispatch:
        inputs:
            PR_number:
                description: 'Pull request number'
                required: true
jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Pull Request Code
      - name: Checkout Pull Request Code
        uses: actions/checkout@v2
        with:
            ref: refs/pull/${{ github.event.inputs.PR_number }}/merge
      
      # Step 2: Deploy to Staging
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./ 
